# name: Version Package Check

# on:
#   push:
#     branches:
#       - "**"

# jobs:
#   check:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Init function
#         run: |
#           chmod +x ./scripts/version-compare.sh

#       # For NodeJS lib
#       - name: Check Node Packages
#         run: |
#           chmod +x ./scripts/node-package-checker.sh
#           ./scripts/node-package-checker.sh
#       # End For NodeJS lib

#       # For Laravel
#       - name: Install Composer
#         uses: docker://composer:2.1
#         with:
#           args: install --no-dev --no-interaction
      
#       - name: Check Laravel Packages
#         run: |
#           chmod +x ./scripts/laravel-package-checker.sh
#           ./scripts/laravel-package-checker.sh
#       # End For Laravel
