name: Package Check

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Install jq
        run: apt install -y jq

      - name: Check Packages
        run: |
          for package in $(jq -r '.dependencies | keys | .[]' package.json); do
            latest_version=$(npm view $package version)
            installed_version=$(jq -r ".dependencies.$package" package.json | cut -c 2-)
            if [[ $installed_version != $latest_version ]]; then
              echo "Error: $package is not in the latest version"
              exit 1
            fi
          done
